# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0002_auto_20170808_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referalnumber',
            name='numbers',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='referaluser',
            name='referal',
            field=models.EmailField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
