# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0003_auto_20170808_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referalnumber',
            old_name='us',
            new_name='ref_user',
        ),
        migrations.RenameField(
            model_name='referaluser',
            old_name='us',
            new_name='user_stat',
        ),
    ]
