# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0004_auto_20170808_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referalnumber',
            old_name='numbers',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='referalnumber',
            name='is_active',
        ),
        migrations.AddField(
            model_name='referalnumber',
            name='use_counter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referalnumber',
            name='ref_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ref.ReferalUser'),
        ),
    ]
