# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0005_auto_20170808_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referalnumber',
            name='use_counter',
        ),
        migrations.AddField(
            model_name='referalnumber',
            name='cost_link',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
